name: cubeenv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python >=3.8
  - setuptools
  - setuptools_scm >=3.4
  - toml
  - pytest-runner
  - sphinx
  - sphinx-click
  - click
  - affine
  - attrs >=18.1
  - botocore
  - boto3
  - cachetools
  - click>=5.0
  - cloudpickle >=0.4.0
  - dask
  - pyproj >=2.5
  - shapely >=2.0
  - jsonschema
  - lark
  - netcdf4
  - numpy
  - pandas
  - psycopg2
  - python-dateutil
  - pyyaml
  - rasterio >=1.3.2
  - ruamel.yaml
  - sqlalchemy <2.0
  - GeoAlchemy2
  - xarray >=0.9
  - toolz
