version: 2
jobs:
  build:
    docker:
      - image: python:3.6
        environment:
          CONDA_ENV_FILE: .travis/environment_py35.yaml
          DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:9.6
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: agdcintegration
          POSTGRES_PASSWORD: ""
    working_directory: ~/datacube-core
    steps:
      - run:
          name: Install Conda + Setup Conda
          working_directory: ~
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -f -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda config --show-sources
            conda config --show
            conda config --prepend channels conda-forge
            conda update --all
            conda info -a

      - checkout

      - run:
          name: Setup Environment
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda env create -q -n agdc --file .travis/environment_py35.yaml
            source activate agdc
            conda install -q sphinx sphinx_rtd_theme mock click # Stuff for docs
            pip install . --no-deps --upgrade

      # - restore_cache:
      #     key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # - run: yarn && pip install -r requirements.txt
      # - save_cache:
      #     key: datacube-core-{{ .Branch }}-{{ checksum "yarn.lock" }}
      #     paths:
      #       - "/home/ubuntu/.yarn-cache"

      - run:
          name: Run All Tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc

            hash -r
            echo $PATH
            echo $(which redis-server)

            pep8 tests integration_tests examples utils --max-line-length 120

            pylint -j 2 --reports no datacube datacube_apps

            # Run tests, taking coverage.
            # Users can specify extra folders as arguments.
            py.test --junitxml=test-reports/pytest-datacube.log -r sx --cov datacube --durations=5 datacube tests datacube_apps integration_tests


      - store_artifacts:
          path: test-reports
          destination: reports

      - store_test_results:
          path: test-reports


      - run:
          name: Build Documentation
          working_directory: ~/datacube-core/docs
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            source activate agdc
            make html

      - store_artifacts:
          path: docs/_build/html
          destination: docs
