name: agdc
channels:
- conda-forge/label/dev
- conda-forge
- defaults
- nodefaults
dependencies:
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- cachetools
- coveralls
- numpy
- numexpr # For AE/EE
- rasterio >= 0.9 # to handle weird 1.0a ordering...
- singledispatch
- netcdf4
- psycopg2
- gdal = 2.1.*        # [py27]
- gdal                # [not py27]
- dask
- xarray
- redis-py # redis client lib, used by celery
- redis # redis server
- pylint # testing
- pep8 # testing
- fiona # movie generator app
- mock # testing
- hypothesis # testing
- matplotlib # pixel drill app
- pathlib
- compliance-checker = 3.0.3
- cython # used by netcdf4 at compile only, but needed for compliance checker to load plugins
- pygeoif = 0.6 # compliance-checker 3.0.3 fails with 0.7
- paramiko # for simple-replicas
- sshtunnel # for simple-replicas
- tqdm # for simple-replicas
- pip:
  - celery >= 4
  - pypeg2
  - pytest-cov # testing
  - pytest-logging
  - pytest-faulthandler

# [py27] is a preprocessing-selector
# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#preprocessing-selectors
