
name: LS5 NBAR

# Any datasets matching these metadata properties.
match:
    metadata:
        platform:
            code: LANDSAT_5
        instrument:
            name: TM
        product_type: NBAR

# Store them using storage definitions '30m_bands' and '15m_bands':
storage:
    - name: 30m_bands
      measurements:
        '10':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_10
        '20':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_20
        '30':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_30
        '40':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_40
        '50':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_50
        '70':
            dtype: int16
            fill_value: -999
            resampling_method: cubic
            varname: band_70
    - name: 15m_band
      measurements:
        '8':
            dtype: int16
            fill_value: -999
            resampling_method: linear
