name: Doc QA
on:
  # Triggers the workflow on pull request events for the main branch
  pull_request:
    branches:
      - 'develop'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pyspell:
    runs-on: ubuntu-latest
    steps:
      # Spellcheck
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: igsekor/pyspelling-any@v1.0.4
        name: Spellcheck

  doctor-rst:
    name: Lint (DOCtor-RST)
    runs-on: ubuntu-latest
    steps:
      -   name: "Checkout"
          uses: actions/checkout@v4

      -   name: "Create cache dir"
          run: mkdir .cache

      -   name: "Extract base branch name"
          run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF##*/}}"
          id: extract_base_branch

      -   name: "Cache DOCtor-RST"
          uses: actions/cache@v4
          with:
              path: .cache
              key: ${{ runner.os }}-doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

      -   name: "Run DOCtor-RST"
          uses: docker://oskarstark/doctor-rst:1.23.0
          with:
              args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache

  documentation-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "datacube-core"
